theme: TranslucentTaskbar
styleConstants:
  - CommonBgBrush=<WindhawkBlur BlurAmount="2" TintColor="#20202020" />
  - IslandBgBrush=<WindhawkBlur BlurAmount="2" TintColor="#40000000" />
  - IslandVerticalMargin=3
  - IslandHorizontalMargin=5
  - TaskbarFrameMaxWidth=5120
controlStyles:
  # Background
  - target: ':root > ScrollViewer > ScrollContentPresenter > Border > Grid'
    styles:
      - Background:=$CommonBgBrush
      - HorizontalAlignment=Stretch
      - ActualWidth=>containerGridWidth
  # Taskbar
  - target: Taskbar.TaskbarFrame
    styles:
      - Width=Auto
      - HorizontalAlignment=Center
      - Margin=0,0,$IslandHorizontalMargin,0
      - Height=50
  - target: Taskbar.TaskbarFrame > Grid
    styles:
      - Background:=$IslandBgBrush
      - CornerRadius=10
      - Margin=0,$IslandVerticalMargin,0,$IslandVerticalMargin
      - Padding=5,0,5,0
  # System tray
  - target: Grid#SystemTrayFrameGrid
    styles:
      - Background:=$IslandBgBrush
      - CornerRadius=10
      - Margin=0,$IslandVerticalMargin,0,$IslandVerticalMargin
      - Padding=5,0,0,0
  # Weather Widget
  - target: Taskbar.TaskListButtonPanel@CommonStates > Border#BackgroundElement
    styles:
      - CornerRadius=10
  # Thumbnail preview background
  - target: Taskbar.TaskbarBackground#HoverFlyoutBackgroundControl > Grid > Rectangle#BackgroundFill
    styles:
      - Fill:=$CommonBgBrush
  # Start button image
  - target: Taskbar.ExperienceToggleButton#LaunchListButton[AutomationProperties.AutomationId=StartButton] > Taskbar.TaskListButtonPanel > Border#BackgroundElement
    styles:
      - Background:=<ImageBrush Stretch="Uniform" ImageSource="E:\Pictures\Íconos\W11SE_Marine_01.png" />
  # Hides Start button animation
  - target: Taskbar.ExperienceToggleButton#LaunchListButton[AutomationProperties.AutomationId=StartButton] > Taskbar.TaskListButtonPanel > Microsoft.UI.Xaml.Controls.AnimatedVisualPlayer#Icon
    styles:
      - Visibility=Collapsed
  # Tray overflow background
  - target: Border#OverflowFlyoutBackgroundBorder
    styles:
      - Background:=$CommonBgBrush
  # Alt+Tab background
  - target: Windows.UI.Xaml.Controls.Grid#ModalRootGrid > Windows.UI.Xaml.Controls.Border#BackgroundElement
    styles:
      - Background:=$IslandBgBrush
  # Task view background
  - target: Windows.UI.Xaml.Controls.Border#BackgroundDimmingLayer
    styles:
      - Background:=$CommonBgBrush
themeResourceVariables:
  - ''
xamlDiagnosticsHandling: ''
