theme: TranslucentShell
styleConstants:
  - CommonBgBrush=<WindhawkBlur BlurAmount="2" TintColor="#60202020" />
controlStyles:
  - target: Grid#NotificationCenterGrid
    styles:
      - Background:=$CommonBgBrush
  - target: Grid#CalendarCenterGrid
    styles:
      - Background:=$CommonBgBrush
  - target: Grid#MediaTransportControlsRegion
    styles:
      - Background:=$CommonBgBrush
themeResourceVariables:
  - ''
resourceVariables:
  - variableKey: ''
    value: ''
